[settings]
# whether to prompt to install plugins and runtimes if they're not already installed
# missing_runtime_behavior = 'warn' # other options: 'ignore', 'warn', 'prompt', 'autoinstall'

# verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
# asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
# jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
# raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr

experimental = true                    # enable experimental features such as shims and core plugins
disable_hints = ["python_precompiled"]
python_compile = false

[tools]
argo = "3"
argocd = "2"
awscli = "2"
bitwarden = "cli-v2025"
chezmoi = "2"
direnv = "2"
golang = "1"
helm = "3"
helm-diff = "3"
helm-docs = "1"
jq = "1"
k9s = "0"
krew = "0"
kubectl = "1"
kubent = "0"
neovim = "0"
pre-commit = "3"
terraform = "1"
terraform-docs = "0"
terraform-validator = "3"
tflint = "0"
tfsec = "1"
tonnage = "0"
usage = "2"
viddy = "1"
yq = "4"
bat = "latest"
fzf = "latest"
ripgrep = "latest"
gh = "latest"
glab = "latest"
uv = "latest"
